### ISSUE TITLE
demo那里,tableView  点击整个cell 那个代理无法响应?

### ISSUE THREAD

**Issue by FaDeve** [937447974/YJCocoa#1]

**Comment by 937447974** [comment]
当前VC调用`[self.tableViewManager addTableViewAOPDelegate:self];`后， 即可使用 tableview 原生代理。tab1界面已支持。

**Comment by FaDeve** [comment]
感谢回复，我是指你定义的那个代理方法无法响应，我看你 demo 那里实现 aop 之后，原生点击是可以的

**Comment by 937447974** [comment]
那个方法？麻烦复制一下

**Comment by FaDeve** [comment]
在 YJFirstViewController 里  - (void)tableViewManager:(YJUITableViewManager *)manager didSelectCellWithCellObject:(YJUITableCellObject *)cellObject  这个方法我发现无法点击整个 cell

**Comment by 937447974** [comment]
可以点击了
```
    self.tableViewManager.delegate = self;
    [self.tableViewManager addTableViewAOPDelegate:self];
```
这两个方法是有顺序的。

**Comment by FaDeve** [comment]
好的，谢谢了


原始邮件
发件人:阳君notifications@github.com
收件人:937447974/YJCocoaYJCocoa@noreply.github.com
抄送:FaDeve2404445663@qq.com; Authorauthor@noreply.github.com
发送时间:2017年10月22日(周日) 01:51
主题:Re: [937447974/YJCocoa] demo那里,tableView 点击整个cell 那个代理无法响应? (#1)


可以点击了
self.tableViewManager.delegate = self; [self.tableViewManager addTableViewAOPDelegate:self];
这两个方法是有顺序的。
